name: 🐛 バグ報告
description: バグを報告する
title: "🐛 "
labels: ["bug"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます。以下の情報を記入してください。

  - type: textarea
    id: description
    attributes:
      label: 📃 バグの説明
      description: バグの内容を明確かつ簡潔に説明してください。
      placeholder: |
        ...が正常な動作をしない。
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: ✅ 再現手順
      description: バグを再現するための手順を記述してください。
      placeholder: |
        1. '...' に移動
        2. '...' をクリック
        3. '...' までスクロール
        4. エラーが発生
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌳 発生した環境
      placeholder: |
        OS：Windows 11 - 25H2
        アプリバージョン：3.0.0 Beta 2 or (Commit) "XXXXXXX"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: ➕ その他の情報
      description: スクリーンショットや参考資料などがあれば追加してください。
    validations:
      required: false
